# -----------------------------------------------------------------------
# NOTE:
# Dependencies are not included as part of Omniperf.
# It's the user's responsibility to accept any licensing implications
# before building the project
# -----------------------------------------------------------------------

version: "3.3"

services:
  web:
    image: omniperf-grafana-v1.1
    container_name: omniperf-grafana-v1.1
    restart: always
    build: .
    environment:
      DOCKER_DEFAULT_PLATFORM: linux/amd64
    ports:
      - "14000:4000"
    volumes:
      - grafana-storage:/var/lib/grafana
    stdin_open: true
    tty: true
  db_mongo:
    container_name: omniperf-mongo
    image: omniperf-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: temp
      MONGO_INITDB_ROOT_PASSWORD: temp123
      DOCKER_DEFAULT_PLATFORM: linux/amd64
    volumes:
      - grafana-mongo-db:/data/db
    ports:
      - "27018:27017"
    command: mongod --bind_ip 0.0.0.0

volumes:
  grafana-mongo-db:
      external: true
  grafana-storage:
      external: true
